# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedoracle',
            name='owner',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='collateral_token',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='factory',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='market',
            name='creator',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='market',
            name='factory',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_maker',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='oracle',
            name='creator',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='oracle',
            name='factory',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='collateral_token',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='outcomevotebalance',
            unique_together=set([('ultimate_oracle', 'address')]),
        ),
    ]
