# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 10:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketShareEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=40)),
                ('net_outcome_tokens_owned', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=80), size=None)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationaldb.Market')),
            ],
        ),
    ]
