# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('resolution_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='categoricaleventdescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoricaleventdescription',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categoricaleventdescription',
            name='resolution_date',
        ),
        migrations.RemoveField(
            model_name='categoricaleventdescription',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='resolution_date',
        ),
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='title',
        ),
        migrations.AlterField(
            model_name='centralizedoracle',
            name='event_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationaldb.EventDescription'),
        ),
        migrations.AddField(
            model_name='categoricaleventdescription',
            name='eventdescription_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relationaldb.EventDescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalareventdescription',
            name='eventdescription_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relationaldb.EventDescription'),
            preserve_default=False,
        ),
    ]
