# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='market',
            unique_together=set([('event', 'market_maker', 'creator')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('sender', 'creation_block')]),
        ),
        migrations.AlterUniqueTogether(
            name='outcomevotebalance',
            unique_together=set([('ultimate_oracle', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='ultimateoracle',
            unique_together=set([('forwarded_oracle', 'collateral_token')]),
        ),
    ]
