# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0002_marketshareentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketshareentry',
            name='market',
        ),
        migrations.DeleteModel(
            name='MarketShareEntry',
        ),
    ]
