# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0002_auto_20171030_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomevotebalance',
            name='ultimate_oracle',
        ),
        migrations.RemoveField(
            model_name='ultimateoracle',
            name='forwarded_oracle',
        ),
        migrations.RemoveField(
            model_name='ultimateoracle',
            name='oracle_ptr',
        ),
        migrations.AddField(
            model_name='centralizedoracle',
            name='old_owner',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='OutcomeVoteBalance',
        ),
        migrations.DeleteModel(
            name='UltimateOracle',
        ),
    ]
