# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0002_auto_20170627_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='redeemed_winnings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='market',
            name='collected_fees',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='market',
            name='funding',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='net_outcome_tokens_sold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=80), size=None),
        ),
        migrations.AlterField(
            model_name='market',
            name='revenue',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='market',
            name='withdrawn_fees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='oracle',
            name='outcome',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_outcome_tokens_sold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=80), size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='outcome_token_count',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='outcometoken',
            name='total_supply',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='outcometokenbalance',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='outcomevotebalance',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalarevent',
            name='lower_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalarevent',
            name='upper_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='profit',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='shortsellorder',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='challenge_amount',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='challenge_period',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='forwarded_outcome',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner_period',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner_set_at_timestamp',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='outcome_set_at_timestamp',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=80, null=True),
        ),
    ]
