# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0002_auto_20170606_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winning_outcome',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='market',
            name='fee',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='market',
            name='funding',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='oracle',
            name='outcome',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalarevent',
            name='lower_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalarevent',
            name='upper_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalareventdescription',
            name='lower_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='scalareventdescription',
            name='upper_bound',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='challenge_amount',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='challenge_period',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='forwarded_outcome',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner_period',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='front_runner_set_at_timestamp',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='outcome_set_at_timestamp',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='spread_multiplier',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ultimateoracle',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
    ]
