# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 06:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0003_auto_20170606_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='lower_bound',
        ),
        migrations.RemoveField(
            model_name='scalareventdescription',
            name='upper_bound',
        ),
        migrations.AddField(
            model_name='categoricaleventdescription',
            name='outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalareventdescription',
            name='decimals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalareventdescription',
            name='unit',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
