# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0003_auto_20170626_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ultimateoracle',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='ultimateoracle',
            index_together=set([('forwarded_oracle', 'collateral_token')]),
        ),
    ]
