# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0003_auto_20170808_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='fees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyorder',
            name='outcome_token_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='fees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='outcome_token_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
            preserve_default=False,
        ),
    ]
