# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0003_auto_20171130_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='marginal_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=5), default=['0.5', '0.5'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='trading_volume',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='relationaldb.Market'),
        ),
        migrations.AlterField(
            model_name='outcometoken',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_tokens', to='relationaldb.Event'),
        ),
    ]
