# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0004_auto_20170817_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marginal_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=5), default=[0, 0], size=None),
            preserve_default=False,
        ),
    ]
