# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0005_order_marginal_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='relationaldb.Event'),
        ),
    ]
