# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0006_auto_20170927_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('creation_date_time', models.DateTimeField()),
                ('creation_block', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('factory', models.CharField(db_index=True, max_length=40)),
                ('creator', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
