# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0006_auto_20170927_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralizedoracle',
            name='old_owner',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
