# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0007_centralizedoracle_old_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomevotebalance',
            name='ultimate_oracle',
        ),
        migrations.RemoveField(
            model_name='ultimateoracle',
            name='forwarded_oracle',
        ),
        migrations.RemoveField(
            model_name='ultimateoracle',
            name='oracle_ptr',
        ),
        migrations.DeleteModel(
            name='OutcomeVoteBalance',
        ),
        migrations.DeleteModel(
            name='UltimateOracle',
        ),
    ]
