# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:38
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0007_auto_20171219_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
