# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0007_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
    ]
