# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0008_tournamentparticipant_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='current_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='diff_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='past_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='predicted_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='predictions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80),
        ),
    ]
