# Generated by Django 2.0.2 on 2018-03-13 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0008_auto_20171219_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='oracle',
            field=models.ForeignKey(db_column='oracle_address', on_delete=django.db.models.deletion.CASCADE, related_name='event_oracle', to='relationaldb.Oracle'),
        ),
        migrations.AlterField(
            model_name='market',
            name='event',
            field=models.ForeignKey(db_column='event_address', on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='relationaldb.Event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(db_column='market_address', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='relationaldb.Market'),
        ),
        migrations.AlterField(
            model_name='order',
            name='outcome_token',
            field=models.ForeignKey(db_column='outcome_token_address', null=True, on_delete=django.db.models.deletion.CASCADE, to='relationaldb.OutcomeToken'),
        ),
        migrations.AlterField(
            model_name='outcometoken',
            name='event',
            field=models.ForeignKey(db_column='event_address', on_delete=django.db.models.deletion.CASCADE, related_name='outcome_tokens', to='relationaldb.Event'),
        ),
        migrations.AlterField(
            model_name='outcometokenbalance',
            name='outcome_token',
            field=models.ForeignKey(db_column='outcome_token_address', on_delete=django.db.models.deletion.CASCADE, to='relationaldb.OutcomeToken'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipantbalance',
            name='participant',
            field=models.OneToOneField(db_column='participant_address', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_balance', to='relationaldb.TournamentParticipant'),
        ),
    ]
