# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0009_auto_20171025_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentWhitelistedCreator',
            fields=[
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tokens_issued',
            field=models.BooleanField(default=False),
        ),
    ]
