# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 15:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0009_auto_20171206_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='marginal_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=5), default=['0.5', '0.5'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='trading_volume',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
