# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0009_auto_20171025_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipantIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField()),
                ('creation_block', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentWhitelistedCreator',
            fields=[
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tokens_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentparticipantissuance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationaldb.TournamentParticipant'),
        ),
    ]
