# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0010_auto_20171030_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='current_rank',
            field=models.IntegerField(),
        ),
    ]
