# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0010_auto_20171206_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='trading_volume',
            field=models.DecimalField(decimal_places=0, max_digits=80),
        ),
    ]
