# Generated by Django 2.0.3 on 2018-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0009_auto_20180313_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='factory',
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='mainnet_address',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
