# Generated by Django 2.1.7 on 2019-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationaldb', '0011_order_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
